-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS MessageProgram;
USE MessageProgram;

-- USER 테이블 생성
CREATE TABLE IF NOT EXISTS USER (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    is_online BOOLEAN DEFAULT FALSE,
    work_status VARCHAR(50) DEFAULT '업무 중',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- SESSION 테이블 생성
CREATE TABLE IF NOT EXISTS SESSION (
    session_id VARCHAR(128) PRIMARY KEY,
    user_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expired_at DATETIME NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE
);
